### ISSUE TITLE
Player goes Idle state in Live stream URL

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [aws-samples/amazon-ivs-player-ios-sample#39] opened 2023-01-30 05:26 UTC
Hi Team, We are using Live Stream (IVS) URL in IVS player (Platform - iOS). We tracked the state and found frequently player state goes to Idle. Once the player goes to idle, until we reinitiate the player, player remains in blank screen. Kindly suggest how to resolve this. @CFKevinRef

**Comment by DineshkumarKandasamy** [comment] 2023-03-29 04:54
Hi Team, Is It possible to auto reload the player once player reached idle or can we increase the waiting time to go idle state? Please suggest @slawrence  @hyandell  @bclymer @tonyjin @CFKevinRef

**Comment by DineshkumarKandasamy** [comment] 2023-03-31 04:42
Hi Team, Can we get any update on this issue?

**Comment by ryanecrist** [comment] 2023-03-31 13:13
Hi @DineshkumarKandasamy, thanks for filing an issue. In order to help us investigate, can you provide the following information?
1. What version of the SDK are you using?
2. Is this issue observable on all iOS versions?
3. Is this issue happening with a particular stream or all streams? VODs vs livestream?
4. Is this issue happening when streaming via AWS IVS or another system?
5. Can you collect debug logs when this issue is observed? You can enable debug logging via the log level property on the player:
```swift
let player = IVSPlayer()
player.logLevel = .debug
```
6. Can you provide a minimal example to reproduce this issue? For example, using one of the demo apps in this repo?
7. Any other useful information you think will help in our investigation.

Thanks!

**Comment by DineshkumarKandasamy** [comment] 2023-04-03 15:24
Hi @ryanecrist Thanks for the update. Please check the details below,

1. What version of the SDK are you using? ->  1.17.0
2. Is this issue observable on all iOS versions? - Yes
3. Is this issue happening with a particular stream or all streams? VODs vs livestream? - All
4. Is this issue happening when streaming via AWS IVS or another system? - Both
5. Can you collect debug logs when this issue is observed? You can enable debug logging via the log level property on the player:
let player = IVSPlayer()
player.logLevel = .debug

how to get this log file to share with you? Please suggest

6. Can you provide a minimal example to reproduce this issue? For example, using one of the demo apps in this repo? 
It happens while any break occur in stream

7. Any other useful information you think will help in our investigation.
In wowza, we can see some drop in live stream. In that time, in player stream stopped. Once the stream started from wowza, to see the live content, we need to reload the player. Is there any way to auto reload and continuous track of incoming stream status?

**Comment by ryanecrist** [comment] 2023-04-04 15:39
Hi @DineshkumarKandasamy, thanks for the information.

5. You can grab logs using the Console application on your mac and then filtering the logs by your host application that is running the AmazonIVSPlayer SDK.
6. So to summarize - the player is only entering the idle stream when the broadcast stops (or is interrupted)? In that case, this sounds like expected behavior, as the stream has concluded (from the player's perspective).
7. At this time, there is no way to auto reload the stream via the SDK. You'll need to have a external mechanism in place to signal to your app that the player needs to call `load()` again on the stream and then `play()`.

**Comment by DineshkumarKandasamy** [comment] 2023-04-04 17:00
Hi @ryanecrist We have integrated log as you have suggested. We have taken this log in low network and player stopped playing. Please check the log below and give your suggestion


2023-04-04 22:15:58.035550+0530 FanaticTV[12730:1170494] [IVSPlayer] VTDecompressionSessionCanAcceptFormatDescription accepted reusing session
2023-04-04 22:15:58.274804+0530 FanaticTV[12730:1170487] [IVSPlayer] text/* track idle
2023-04-04 22:15:59.611545+0530 FanaticTV[12730:1170494] [IVSPlayer] Track video : idle at 11347179 us
2023-04-04 22:15:59.611795+0530 FanaticTV[12730:1170494] [IVSPlayer] video/* track idle
2023-04-04 22:15:59.612483+0530 FanaticTV[12730:1170485] [IVSPlayer] audio/* awaitIdle
2023-04-04 22:15:59.612556+0530 FanaticTV[12730:1170485] [IVSPlayer] text/* awaitIdle
2023-04-04 22:15:59.613062+0530 FanaticTV[12730:1170493] [IVSPlayer] AudioQueue create new output
2023-04-04 22:15:59.613259+0530 FanaticTV[12730:1170485] [IVSPlayer] video/* awaitIdle
2023-04-04 22:15:59.613316+0530 FanaticTV[12730:1170485] [IVSPlayer] Player rebuffering... position: 11003166
2023-04-04 22:15:59.616077+0530 FanaticTV[12730:1170485] [IVSPlayer] BufferState changed Refilling
2023-04-04 22:15:59.616154+0530 FanaticTV[12730:1170485] [IVSPlayer] soun buffer ranges 0.000000-11.370667
2023-04-04 22:15:59.616186+0530 FanaticTV[12730:1170485] [IVSPlayer] vide buffer ranges 0.000000-11.343000
2023-04-04 22:15:59.616259+0530 FanaticTV[12730:1170485] [IVSPlayer] normal fast 924.431 kbps slow 1128.907 kbps
2023-04-04 22:15:59.616295+0530 FanaticTV[12730:1170485] [IVSPlayer] Rebuffer 908.97 kbps in 1.48 s with 908.97 kbps in 2.46 s estimated 924.43 kbps
2023-04-04 22:15:59.616351+0530 FanaticTV[12730:1170485] [IVSPlayer] Player state changed Playing to Buffering
2023-04-04 22:15:59.635397+0530 FanaticTV[12730:1170493] [IVSPlayer] Track audio : idle at 11003166 us
2023-04-04 22:15:59.635469+0530 FanaticTV[12730:1170493] [IVSPlayer] audio/* track idle
2023-04-04 22:16:07.104983+0530 FanaticTV[12730:1170485] [IVSPlayer] normal fast 924.431 kbps slow 1128.907 kbps
2023-04-04 22:16:07.105060+0530 FanaticTV[12730:1170485] [IVSPlayer] ABR downloaded Video:4405 transferred 77.789 kbps (11.00 s), bandwidth estimate 924.431 kbps
2023-04-04 22:16:07.105153+0530 FanaticTV[12730:1170485] [IVSPlayer] Player recoverable error Video:4405:9 (ErrorNetworkIO code -1001 - The request timed out.)
2023-04-04 22:16:09.210227+0530 FanaticTV[12730:1170485] [IVSPlayer] start segment prefetch 4405/4405 [0] stream chunked (Video)
2023-04-04 22:16:09.221242+0530 FanaticTV[12730:1170396] Connection 96: received failure notification
2023-04-04 22:16:09.221404+0530 FanaticTV[12730:1170396] Connection 96: failed to connect 12:8, reason -1
2023-04-04 22:16:09.221484+0530 FanaticTV[12730:1170396] Connection 96: encountered error(12:8)
2023-04-04 22:16:09.225719+0530 FanaticTV[12730:1170485] [IVSPlayer] normal fast 924.431 kbps slow 1128.907 kbps
2023-04-04 22:16:09.225815+0530 FanaticTV[12730:1170485] [IVSPlayer] ABR downloaded Video:4405 transferred 0.000 kbps (394365.35 s), bandwidth estimate 924.431 kbps
2023-04-04 22:16:09.225856+0530 FanaticTV[12730:1170485] [IVSPlayer] Player recoverable error Video:4405:9 (ErrorNetworkIO code -1003 - A server with the specified hostname could not be found.)
2023-04-04 22:16:13.243060+0530 FanaticTV[12730:1170485] [IVSPlayer] start segment prefetch 4405/4405 [0] stream chunked (Video)
2023-04-04 22:16:13.253640+0530 FanaticTV[12730:1170162] Connection 97: received failure notification
2023-04-04 22:16:13.253838+0530 FanaticTV[12730:1170162] Connection 97: failed to connect 12:8, reason -1
2023-04-04 22:16:13.253947+0530 FanaticTV[12730:1170162] Connection 97: encountered error(12:8)
2023-04-04 22:16:13.257945+0530 FanaticTV[12730:1170485] [IVSPlayer] normal fast 924.431 kbps slow 1128.907 kbps
2023-04-04 22:16:13.258004+0530 FanaticTV[12730:1170485] [IVSPlayer] ABR downloaded Video:4405 transferred 0.000 kbps (394369.39 s), bandwidth estimate 924.431 kbps
2023-04-04 22:16:13.258068+0530 FanaticTV[12730:1170485] [IVSPlayer] Player stopping playback - error Video:4405:9 (ErrorNetworkIO code -1003 - A server with the specified hostname could not be found.)
2023-04-04 22:16:13.258215+0530 FanaticTV[12730:1170493] [IVSPlayer] Track audio : destroying
2023-04-04 22:16:13.261153+0530 FanaticTV[12730:1170485] [IVSPlayer] Player Track audio destructor
2023-04-04 22:16:13.261977+0530 FanaticTV[12730:1170494] [IVSPlayer] Track video : destroying
2023-04-04 22:16:13.272981+0530 FanaticTV[12730:1170485] [IVSPlayer] Player Track video destructor
2023-04-04 22:16:13.273825+0530 FanaticTV[12730:1170487] [IVSPlayer] Track text : destroying
2023-04-04 22:16:13.273873+0530 FanaticTV[12730:1170485] [IVSPlayer] Player Track text destructor
2023-04-04 22:16:13.274158+0530 FanaticTV[12730:1170485] [IVSPlayer] Player state changed Buffering to Idle
2023-04-04 22:16:19.191088+0530 FanaticTV[12730:1170396] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C82] Hit maximum timestamp count, will start dropping events
2023-04-04 22:16:19.208179+0530 FanaticTV[12730:1170396] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C79] Hit maximum timestamp count, will start dropping events
2023-04-04 22:16:21.550535+0530 FanaticTV[12730:1170503] [tcp] tcp_input [C65.1.1:2] flags=[R.] seq=2954175048, ack=3189632196, win=4096 state=FIN_WAIT_1 rcv_nxt=2954175048, snd_una=3189632159
2023-04-04 22:16:32.565536+0530 FanaticTV[12730:1170396] Task <A50DCE1E-2839-421E-9DA1-723511B778DB>.<23> HTTP load failed, 2460/0 bytes (error code: -1017 [4:-1])
2023-04-04 22:16:32.565918+0530 FanaticTV[12730:1170396] Task <D12E75F6-2A9E-4DC1-B91B-92E7DE5A9B17>.<24> HTTP load failed, 2544/0 bytes (error code: -1017 [4:-1])
2023-04-04 22:16:32.566275+0530 FanaticTV[12730:1170396] Task <F061342D-F53D-4DC1-ADE9-EB38DACB5B5E>.<25> HTTP load failed, 3092/0 bytes (error code: -1017 [4:-1])
2023-04-04 22:16:32.574286+0530 FanaticTV[12730:1170485] [IVSPlayer] SpadeClient send error -1017 : cannot parse response
2023-04-04 22:16:32.574821+0530 FanaticTV[12730:1170485] [IVSPlayer] SpadeClient send error -1017 : cannot parse response
2023-04-04 22:16:32.583012+0530 FanaticTV[12730:1170485] [IVSPlayer] SpadeClient send error -1017 : cannot parse response

**Comment by ryanecrist** [comment] 2023-04-04 21:00
Hi @DineshkumarKandasamy,

From the logs you provided the player is stopping playback due to inadequate network conditions. When this happens, the only way to recover is to reload the playback URL and call `play()` again on the player (though I'd suggest doing so when your app determines that network conditions are adequate again).

I'm going to close this issue as there doesn't appear to be an issue with the AmazonIVSPlayer SDK itself. For additional help with your particular use case, please reach out via your AWS support plan. If you find what you believe to be an issue with the SDK, please reopen this issue or file a new one.

**Closed as completed by ryanecrist** 2023-04-04 21:00 UTC

**Comment by DineshkumarKandasamy** [comment] 2023-04-07 11:32
Hi @ryanecrist  Can we get the player log's from the Test flight released build? We could not able to reproduce the issue, while we try to run the app in local. Kindly suggest
